{
  "swagger": "2.0",
  "schemes": [
    "https"
  ],
  "host": "api.atlassian.com/ex/jira",
  "basePath": "/{cloudid}/rest/api/3",
  "info": {
    "contact": {
      "email": "ecosystem@atlassian.com"
    },
    "description": "Jira Cloud platform REST API documentation",
    "title": "The Jira Cloud platform REST API",
    "version": "1001.0.0-SNAPSHOT",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "termsOfService": "http://atlassian.com/terms/"
  },
  "x-atlassian-narrative": {
    "documents": [
      {
        "anchor": "about",
        "body": "The Jira REST API enables you to interact with Jira programmatically. Use this API to \n[build apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/), script interactions with \nJira, or develop any other type of integration. This page documents the REST resources available in Jira Cloud, including \nthe HTTP response codes and example requests and responses.",
        "title": "About"
      },
      {
        "anchor": "version",
        "body": "This documentation is for **version 3** of the Jira Cloud platform REST API, which is the latest version. \n\nThe URIs for resources have the following structure:\n\n`https://<site-url>/rest/api/3/<resource-name>`\n\nFor example,\n`https://your-domain.atlassian.net/rest/api/3/issue/DEMO-1`\n\n**Note that version 3 of the Jira Cloud platform REST API is in beta**. All the endpoints from the \n[version 2](https://developer.atlassian.com/cloud/jira/platform/rest/v2/) API are availa[...]",
        "title": "Version and URI"
      },
      {
        "anchor": "authentication",
        "body": "### Connect apps\n\nFor Connect apps, authentication (JWT-based) is built into the Connect libraries. Authorization is implemented using either \nscopes (shown as _App scope required_ for operations on this page) or user impersonation. See \n[Security for Connect apps](https://developer.atlassian.com/cloud/jira/platform/security-for-connect-apps/) \nfor details.\n\n### Other integrations\n\nFor integrations that are not Connect apps, use OAuth 2.0 authorization code grants (3LO)[...]",
        "title": "Authentication and authorization"
      },
      {
        "anchor": "permissions",
        "body": "### Operation permissions\n\nMost operations in this API require permissions. The calling user must have the required permissions for an operation to \nuse it. Note that for Connect apps, the app user must have the required permissions for the operation and the app must \nhave scopes that permit the operation.\n\nA permission can be granted to a group, project role, or issue role that the user is a member of, or granted directly to a user. \nSee [Permissions overview](https://co[...]",
        "title": "Permissions"
      },
      {
        "anchor": "expansion",
        "body": "### Expansion\n\nThe Jira REST API uses resource expansion, which means that some parts of a resource are not returned unless specified \nin the request. This simplifies responses and minimizes network traffic.\n\nTo expand part of a resource in a request, use the expand query parameter and specify the object(s) to be expanded. \nIf you need to expand nested objects, use the `.` dot notation. If you need to expand multiple objects, use a \ncomma-separated list. \n\nFor example, [...]",
        "title": "Expansion, pagination, and ordering"
      },
      {
        "anchor": "special-request-headers",
        "body": "The following request and response headers define important metadata for the Jira Cloud REST API resources.\n\n-   `X-Atlassian-Token` (request): Operations that accept multipart/form-data must include the `X-Atlassian-Token: no-check`\nheader in requests. Otherwise the request will be blocked by cross-site request forgery (CSRF/XSRF) protection.\n-   `X-Force-Accept-Language` (request): controls how the standard HTTP `Accept-Language` header is processed.\nBy default `Accept-La[...]",
        "title": "Special headers"
      },
      {
        "anchor": "anonymous-operations",
        "body": " Jira provides for all permissions, except the [global permission](https://confluence.atlassian.com/x/x4dKLg) Administer Jira, to be assigned to *Anyone*. Once a permission is assigned to *Anyone*, anyone knowing a project's URL is able to use the features in Jira enabled by the permission. However, the Jira REST API does not enable anonymous access for operations by default. This means that an anonymous user who may be able to perform an action through Jira, may not be able to [...]",
        "title": "Anonymous operations"
      },
      {
        "anchor": "async-operations",
        "body": "Some Jira REST API operations may trigger long-running or computationally expensive tasks. In these cases, the operation \nwill schedule an asynchronous task and return a `303 (See Other)` response, indicating the location of the queued task \nin the `Location` header. You can query this task to get progress updates.\n\nWhen the task finishes, the response object will contain the `result` field. The content of the field is specific to the \noperation that created the task. Refer[...]",
        "title": "Asynchronous operations"
      },
      {
        "anchor": "experimental",
        "body": "Features and methods marked as experimental may change without notice. Feedback on experimental functionality is welcome. \nReport your suggestions and bugs in the [ACJIRA project](https://ecosystem.atlassian.net/projects/ACJIRA) (preferred) or use the \n**Give docs feedback** link at the top of this page. \n",
        "title": "Experimental features"
      },
      {
        "anchor": "status-codes",
        "body": "The Jira Cloud platform REST API uses the [standard HTTP status codes](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html).\n\nOperations that return an error status code may also return a response body containing details of the error or errors. \nThe schema for the response body is shown below:\n\n\n```json\n{\n  \"id\": \"https://docs.atlassian.com/jira/REST/schema/error-collection#\",\n  \"title\": \"Error Collection\",\n  \"type\": \"object\",\n  \"properties\": {\n    [...]",
        "title": "Status codes"
      }
    ]
  },
  "x-components": {},
  "securityDefinitions": {
    "OAuth2": {
      "authorizationUrl": "https://auth.atlassian.com/authorize",
      "description": "OAuth2 scopes for Jira",
      "flow": "accessCode",
      "scopes": {
        "manage:jira-configuration": "Configure Jira settings that require the Jira administrators permission, for example, create projects and custom fields, view workflows, manage issue link types.",
        "manage:jira-project": "Create and edit project settings and create new project-level objects, for example, versions, components.",
        "read:jira-user": "View user information in Jira that you have access to, including usernames, email addresses, and avatars.",
        "read:jira-work": "Read project and issue data. Search for issues and objects associated with issues (such as attachments and worklogs).",
        "write:jira-work": "Create and edit issues in Jira, post comments, create worklogs, and delete issues."
      },
      "tokenUrl": "https://auth.atlassian.com/oauth/token",
      "type": "oauth2"
    },
    "basicAuth": {
      "description": "You can access this resource via basic auth.",
      "type": "basic"
    }
  },
  "paths": {
    "/application-properties": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Jira settings"
        ],
        "deprecated": false,
        "summary": "Get application property",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/application-properties/advanced-settings": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Jira settings"
        ],
        "deprecated": false,
        "summary": "Get advanced settings",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/application-properties/{id}": {
      "put": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Jira settings"
        ],
        "deprecated": false,
        "summary": "Set application property",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/applicationrole": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Application roles"
        ],
        "deprecated": false,
        "summary": "Get all application roles",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/applicationrole/{key}": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Application roles"
        ],
        "deprecated": false,
        "summary": "Get application role",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/attachment/meta": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue attachments"
        ],
        "deprecated": false,
        "summary": "Get Jira attachment settings",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/attachment/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue attachments"
        ],
        "deprecated": false,
        "summary": "Delete attachment",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue attachments"
        ],
        "deprecated": false,
        "summary": "Get attachment metadata",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/attachment/{id}/expand/human": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue attachments"
        ],
        "deprecated": false,
        "summary": "Get all metadata for an expanded attachment",
        "x-atlassian-connect-scope": "READ",
        "x-experimental": true
      }
    },
    "/attachment/{id}/expand/raw": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue attachments"
        ],
        "deprecated": false,
        "summary": "Get contents metadata for an expanded attachment",
        "x-atlassian-connect-scope": "READ",
        "x-experimental": true
      }
    },
    "/auditing/record": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Audit records"
        ],
        "deprecated": false,
        "summary": "Get audit records",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/avatar/{type}/system": {
      "get": {
        "security": [
          {}
        ],
        "tags": [
          "Avatars"
        ],
        "deprecated": false,
        "summary": "Get system avatars by type",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/comment/list": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue comments"
        ],
        "deprecated": false,
        "summary": "Get comments by IDs",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/comment/{commentId}/properties": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue comment properties"
        ],
        "deprecated": false,
        "summary": "Get comment property keys",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/comment/{commentId}/properties/{propertyKey}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue comment properties"
        ],
        "deprecated": false,
        "summary": "Delete comment property",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue comment properties"
        ],
        "deprecated": false,
        "summary": "Get comment property",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue comment properties"
        ],
        "deprecated": false,
        "summary": "Set comment property",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/component": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project components"
        ],
        "deprecated": false,
        "summary": "Create component",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/component/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project components"
        ],
        "deprecated": false,
        "summary": "Delete component",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project components"
        ],
        "deprecated": false,
        "summary": "Get component",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project components"
        ],
        "deprecated": false,
        "summary": "Update component",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/component/{id}/relatedIssueCounts": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project components"
        ],
        "deprecated": false,
        "summary": "Get component issues count",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/configuration": {
      "get": {
        "security": [
          {}
        ],
        "tags": [
          "Jira settings"
        ],
        "deprecated": false,
        "summary": "Get global settings",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/configuration/timetracking": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Time tracking"
        ],
        "deprecated": false,
        "summary": "Get selected time tracking provider",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Time tracking"
        ],
        "deprecated": false,
        "summary": "Select time tracking provider",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/configuration/timetracking/list": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Time tracking"
        ],
        "deprecated": false,
        "summary": "Get all time tracking providers",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/configuration/timetracking/options": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Time tracking"
        ],
        "deprecated": false,
        "summary": "Get time tracking settings",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Time tracking"
        ],
        "deprecated": false,
        "summary": "Set time tracking settings",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/customField/{fieldId}/option": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue custom field options"
        ],
        "deprecated": false,
        "summary": "Get options for field",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue custom field options"
        ],
        "deprecated": false,
        "summary": "Create custom field options",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue custom field options"
        ],
        "deprecated": false,
        "summary": "Update custom field options",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/customFieldOption/{id}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue custom field options"
        ],
        "deprecated": false,
        "summary": "Get custom field option",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/dashboard": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Get all dashboards",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Create dashboard",
        "x-atlassian-connect-scope": "WRITE",
        "x-experimental": true
      }
    },
    "/dashboard/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Search for dashboards",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/dashboard/{dashboardId}/items/{itemId}/properties": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Get dashboard item property keys",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Delete dashboard item property",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Get dashboard item property",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Set dashboard item property",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/dashboard/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Delete dashboard",
        "x-atlassian-connect-scope": "DELETE",
        "x-experimental": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Get dashboard",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Update dashboard",
        "x-atlassian-connect-scope": "WRITE",
        "x-experimental": true
      }
    },
    "/dashboard/{id}/copy": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Dashboards"
        ],
        "deprecated": false,
        "summary": "Copy dashboard",
        "x-atlassian-connect-scope": "WRITE",
        "x-experimental": true
      }
    },
    "/expression/analyse": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work",
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "Jira expressions"
        ],
        "deprecated": false,
        "summary": "Analyse Jira expression",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/expression/eval": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work",
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "Jira expressions"
        ],
        "deprecated": false,
        "summary": "Evaluate Jira expression",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/field": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue fields"
        ],
        "deprecated": false,
        "summary": "Get fields",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Issue fields"
        ],
        "deprecated": false,
        "summary": "Create custom field",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/field/search": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Issue fields"
        ],
        "deprecated": false,
        "summary": "Get fields paginated",
        "x-atlassian-connect-scope": "NONE",
        "x-experimental": true
      }
    },
    "/field/{fieldId}/contexts": {
      "get": {
        "security": [
          {}
        ],
        "tags": [
          "Issue fields"
        ],
        "deprecated": false,
        "summary": "Get contexts for a field",
        "x-atlassian-connect-scope": "NONE",
        "x-experimental": true
      }
    },
    "/field/{fieldId}/screens": {
      "get": {
        "security": [
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Get screens for a field",
        "x-atlassian-connect-scope": "NONE"
      }
    },
    "/field/{fieldKey}/option": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue custom field options (apps)"
        ],
        "deprecated": false,
        "summary": "Get all issue field options",
        "x-atlassian-connect-scope": "NONE"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue custom field options (apps)"
        ],
        "deprecated": false,
        "summary": "Create issue field option",
        "x-atlassian-connect-scope": "NONE"
      }
    },
    "/field/{fieldKey}/option/suggestions/edit": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue custom field options (apps)"
        ],
        "deprecated": false,
        "summary": "Get selectable issue field options",
        "x-atlassian-connect-scope": "NONE"
      }
    },
    "/field/{fieldKey}/option/suggestions/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue custom field options (apps)"
        ],
        "deprecated": false,
        "summary": "Get visible issue field options",
        "x-atlassian-connect-scope": "NONE"
      }
    },
    "/field/{fieldKey}/option/{optionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue custom field options (apps)"
        ],
        "deprecated": false,
        "summary": "Delete issue field option",
        "x-atlassian-connect-scope": "NONE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue custom field options (apps)"
        ],
        "deprecated": false,
        "summary": "Get issue field option",
        "x-atlassian-connect-scope": "NONE"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue custom field options (apps)"
        ],
        "deprecated": false,
        "summary": "Update issue field option",
        "x-atlassian-connect-scope": "NONE"
      }
    },
    "/field/{fieldKey}/option/{optionId}/issue": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue custom field options (apps)"
        ],
        "deprecated": false,
        "summary": "Replace issue field option",
        "x-atlassian-connect-scope": "NONE"
      }
    },
    "/fieldconfiguration": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue field configurations"
        ],
        "deprecated": false,
        "summary": "Get all field configurations",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/fieldconfiguration/{id}/fields": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue field configurations"
        ],
        "deprecated": false,
        "summary": "Get field configuration items",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/fieldconfigurationscheme": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue field configurations"
        ],
        "deprecated": false,
        "summary": "Get all field configuration schemes",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/fieldconfigurationscheme/mapping": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue field configurations"
        ],
        "deprecated": false,
        "summary": "Get field configuration issue type items",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/fieldconfigurationscheme/project": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue field configurations"
        ],
        "deprecated": false,
        "summary": "Get field configuration schemes for projects",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue field configurations"
        ],
        "deprecated": false,
        "summary": "Assign field configuration scheme to project",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/filter": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": true,
        "summary": "Get filters",
        "x-atlassian-connect-scope": "READ",
        "x-changes": [
          {
            "announced": "2018-10-19T00:00:00.000Z",
            "details": "https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-removal-of-get-filters-and-get-all-projects/",
            "effective": "2019-04-19T00:00:00.000Z",
            "type": "removed"
          }
        ]
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Create filter",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/filter/defaultShareScope": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Filter sharing"
        ],
        "deprecated": false,
        "summary": "Get default share scope",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Filter sharing"
        ],
        "deprecated": false,
        "summary": "Set default share scope",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/filter/favourite": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Get favorite filters",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/filter/my": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Get my filters",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/filter/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Search for filters",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/filter/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Delete filter",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Get filter",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Update filter",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/filter/{id}/columns": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Reset columns",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Get columns",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Set columns",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/filter/{id}/favourite": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Remove filter as favorite",
        "x-atlassian-connect-scope": "DELETE"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Filters"
        ],
        "deprecated": false,
        "summary": "Add filter as favorite",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/filter/{id}/permission": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Filter sharing"
        ],
        "deprecated": false,
        "summary": "Get share permissions",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Filter sharing"
        ],
        "deprecated": false,
        "summary": "Add share permission",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/filter/{id}/permission/{permissionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Filter sharing"
        ],
        "deprecated": false,
        "summary": "Delete share permission",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Filter sharing"
        ],
        "deprecated": false,
        "summary": "Get share permission",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/group": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Groups"
        ],
        "deprecated": false,
        "summary": "Remove group",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "tags": [
          "Groups"
        ],
        "deprecated": true,
        "summary": "Get group",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Groups"
        ],
        "deprecated": false,
        "summary": "Create group",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/group/member": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Groups"
        ],
        "deprecated": false,
        "summary": "Get users from group",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/group/user": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Groups"
        ],
        "deprecated": false,
        "summary": "Remove user from group",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Groups"
        ],
        "deprecated": false,
        "summary": "Add user to group",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/groups/picker": {
      "get": {
        "security": [
          {}
        ],
        "tags": [
          "Groups"
        ],
        "deprecated": false,
        "summary": "Find groups",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/groupuserpicker": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Group and user picker"
        ],
        "deprecated": false,
        "summary": "Find users and groups",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/issue": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Create issue",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/bulk": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Bulk create issue",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/createmeta": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Get create issue metadata",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/issue/picker": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue search"
        ],
        "deprecated": false,
        "summary": "Get issue picker suggestions",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/issue/properties": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue properties"
        ],
        "deprecated": false,
        "summary": "Bulk set issues properties",
        "x-atlassian-connect-scope": "WRITE",
        "x-experimental": true
      }
    },
    "/issue/properties/{propertyKey}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue properties"
        ],
        "deprecated": false,
        "summary": "Bulk delete issue property",
        "x-atlassian-connect-scope": "DELETE"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue properties"
        ],
        "deprecated": false,
        "summary": "Bulk set issue property",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Delete issue",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Get issue",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Edit issue",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/assignee": {
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Assign issue",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/attachments": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue attachments"
        ],
        "deprecated": false,
        "summary": "Add attachment",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/changelog": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Get change logs",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/issue/{issueIdOrKey}/comment": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue comments"
        ],
        "deprecated": false,
        "summary": "Get comments",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue comments"
        ],
        "deprecated": false,
        "summary": "Add comment",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/comment/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue comments"
        ],
        "deprecated": false,
        "summary": "Delete comment",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue comments"
        ],
        "deprecated": false,
        "summary": "Get comment",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue comments"
        ],
        "deprecated": false,
        "summary": "Update comment",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/editmeta": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Get edit issue metadata",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/issue/{issueIdOrKey}/notify": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Send notification for issue",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/properties": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue properties"
        ],
        "deprecated": false,
        "summary": "Get issue property keys",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/issue/{issueIdOrKey}/properties/{propertyKey}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue properties"
        ],
        "deprecated": false,
        "summary": "Delete issue property",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue properties"
        ],
        "deprecated": false,
        "summary": "Get issue property",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue properties"
        ],
        "deprecated": false,
        "summary": "Set issue property",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/remotelink": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue remote links"
        ],
        "deprecated": false,
        "summary": "Delete remote issue link by global ID",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue remote links"
        ],
        "deprecated": false,
        "summary": "Get remote issue links",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue remote links"
        ],
        "deprecated": false,
        "summary": "Create or update remote issue link",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/remotelink/{linkId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue remote links"
        ],
        "deprecated": false,
        "summary": "Delete remote issue link by ID",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue remote links"
        ],
        "deprecated": false,
        "summary": "Get remote issue link by ID",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue remote links"
        ],
        "deprecated": false,
        "summary": "Update remote issue link by ID",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/transitions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Get transitions",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issues"
        ],
        "deprecated": false,
        "summary": "Transition issue",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/votes": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue votes"
        ],
        "deprecated": false,
        "summary": "Delete vote",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue votes"
        ],
        "deprecated": false,
        "summary": "Get votes",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue votes"
        ],
        "deprecated": false,
        "summary": "Add vote",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/watchers": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue watchers"
        ],
        "deprecated": false,
        "summary": "Delete watcher",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue watchers"
        ],
        "deprecated": false,
        "summary": "Get issue watchers",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue watchers"
        ],
        "deprecated": false,
        "summary": "Add watcher",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/worklog": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue worklogs"
        ],
        "deprecated": false,
        "summary": "Get issue worklogs",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue worklogs"
        ],
        "deprecated": false,
        "summary": "Add worklog",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/worklog/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue worklogs"
        ],
        "deprecated": false,
        "summary": "Delete worklog",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue worklogs"
        ],
        "deprecated": false,
        "summary": "Get worklog",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue worklogs"
        ],
        "deprecated": false,
        "summary": "Update worklog",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issue/{issueIdOrKey}/worklog/{worklogId}/properties": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue worklog properties"
        ],
        "deprecated": false,
        "summary": "Get worklog property keys",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue worklog properties"
        ],
        "deprecated": false,
        "summary": "Delete worklog property",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue worklog properties"
        ],
        "deprecated": false,
        "summary": "Get worklog property",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue worklog properties"
        ],
        "deprecated": false,
        "summary": "Set worklog property",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issueLink": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue links"
        ],
        "deprecated": false,
        "summary": "Create issue link",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/issueLink/{linkId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue links"
        ],
        "deprecated": false,
        "summary": "Delete issue link",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue links"
        ],
        "deprecated": false,
        "summary": "Get issue link",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/issueLinkType": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue link types"
        ],
        "deprecated": false,
        "summary": "Get issue link types",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Issue link types"
        ],
        "deprecated": false,
        "summary": "Create issue link type",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/issueLinkType/{issueLinkTypeId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Issue link types"
        ],
        "deprecated": false,
        "summary": "Delete issue link type",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue link types"
        ],
        "deprecated": false,
        "summary": "Get issue link type",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {}
        ],
        "tags": [
          "Issue link types"
        ],
        "deprecated": false,
        "summary": "Update issue link type",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/issuesecurityschemes": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Issue security schemes"
        ],
        "deprecated": false,
        "summary": "Get issue security schemes",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/issuesecurityschemes/{id}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Issue security schemes"
        ],
        "deprecated": false,
        "summary": "Get issue security scheme",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/issuesecurityschemes/{issueSecuritySchemeId}/members": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Issue security level"
        ],
        "deprecated": false,
        "summary": "Get issue security level members",
        "x-atlassian-connect-scope": "PROJECT_ADMIN",
        "x-experimental": true
      }
    },
    "/issuetype": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue types"
        ],
        "deprecated": false,
        "summary": "Get all issue types for user",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Issue types"
        ],
        "deprecated": false,
        "summary": "Create issue type",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/issuetype/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Issue types"
        ],
        "deprecated": false,
        "summary": "Delete issue type",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue types"
        ],
        "deprecated": false,
        "summary": "Get issue type",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Issue types"
        ],
        "deprecated": false,
        "summary": "Update issue type",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/issuetype/{id}/alternatives": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue types"
        ],
        "deprecated": false,
        "summary": "Get alternative issue types",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/issuetype/{id}/avatar2": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Issue types"
        ],
        "deprecated": false,
        "summary": "Load issue type avatar",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/issuetype/{issueTypeId}/properties": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue type properties"
        ],
        "deprecated": false,
        "summary": "Get issue type property keys",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/issuetype/{issueTypeId}/properties/{propertyKey}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Issue type properties"
        ],
        "deprecated": false,
        "summary": "Delete issue type property",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue type properties"
        ],
        "deprecated": false,
        "summary": "Get issue type property",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Issue type properties"
        ],
        "deprecated": false,
        "summary": "Set issue type property",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/issuetypescheme": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue type schemes"
        ],
        "deprecated": false,
        "summary": "Get all issue type schemes",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/issuetypescheme/mapping": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue type schemes"
        ],
        "deprecated": false,
        "summary": "Get issue type scheme items",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/issuetypescheme/project": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue type schemes"
        ],
        "deprecated": false,
        "summary": "Get issue type schemes for projects",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue type schemes"
        ],
        "deprecated": false,
        "summary": "Assign issue type scheme to project",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/issuetypescreenscheme": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue type screen schemes"
        ],
        "deprecated": false,
        "summary": "Get issue type screen schemes",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/issuetypescreenscheme/mapping": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue type screen schemes"
        ],
        "deprecated": false,
        "summary": "Get issue type screen scheme items",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/issuetypescreenscheme/project": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue type screen schemes"
        ],
        "deprecated": false,
        "summary": "Get issue type screen schemes for projects",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue type screen schemes"
        ],
        "deprecated": false,
        "summary": "Assign issue type screen scheme to project",
        "x-atlassian-connect-scope": "ADMIN",
        "x-experimental": true
      }
    },
    "/jql/autocompletedata": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "JQL"
        ],
        "deprecated": false,
        "summary": "Get field reference data",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/jql/autocompletedata/suggestions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "JQL"
        ],
        "deprecated": false,
        "summary": "Get field auto complete suggestions",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/jql/match": {
      "post": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Issue search"
        ],
        "deprecated": false,
        "summary": "Check issues against JQL",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/jql/parse": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "JQL"
        ],
        "deprecated": false,
        "summary": "Parse JQL query",
        "x-atlassian-connect-scope": "READ",
        "x-experimental": true
      }
    },
    "/jql/pdcleaner": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "tags": [
          "JQL"
        ],
        "deprecated": false,
        "summary": "Convert user identifiers to account IDs in JQL queries",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/label": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Labels"
        ],
        "deprecated": false,
        "summary": "Get all labels",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/mypermissions": {
      "get": {
        "security": [
          {
            "OAuth2": []
          },
          {}
        ],
        "tags": [
          "Permissions"
        ],
        "deprecated": false,
        "summary": "Get my permissions",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/mypreferences": {
      "delete": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Myself"
        ],
        "deprecated": false,
        "summary": "Delete preference",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Myself"
        ],
        "deprecated": false,
        "summary": "Get preference",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "put": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Myself"
        ],
        "deprecated": false,
        "summary": "Set preference",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/mypreferences/locale": {
      "delete": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Myself"
        ],
        "deprecated": true,
        "summary": "Delete locale",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "get": {
        "security": [
          {}
        ],
        "tags": [
          "Myself"
        ],
        "deprecated": false,
        "summary": "Get locale",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "put": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Myself"
        ],
        "deprecated": true,
        "summary": "Set locale",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/myself": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "tags": [
          "Myself"
        ],
        "deprecated": false,
        "summary": "Get current user",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/notificationscheme": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue notification schemes"
        ],
        "deprecated": false,
        "summary": "Get notification schemes paginated",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/notificationscheme/{id}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Issue notification schemes"
        ],
        "deprecated": false,
        "summary": "Get notification scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/permissions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Permissions"
        ],
        "deprecated": false,
        "summary": "Get all permissions",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/permissions/check": {
      "post": {
        "security": [
          {
            "OAuth2": []
          },
          {}
        ],
        "tags": [
          "Permissions"
        ],
        "deprecated": false,
        "summary": "Get bulk permissions",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/permissions/project": {
      "post": {
        "security": [
          {
            "OAuth2": []
          },
          {}
        ],
        "tags": [
          "Permissions"
        ],
        "deprecated": false,
        "summary": "Get permitted projects",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/permissionscheme": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Permission schemes"
        ],
        "deprecated": false,
        "summary": "Get all permission schemes",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Permission schemes"
        ],
        "deprecated": false,
        "summary": "Create permission scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/permissionscheme/{schemeId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Permission schemes"
        ],
        "deprecated": false,
        "summary": "Delete permission scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Permission schemes"
        ],
        "deprecated": false,
        "summary": "Get permission scheme",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Permission schemes"
        ],
        "deprecated": false,
        "summary": "Update permission scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/permissionscheme/{schemeId}/permission": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Permission schemes"
        ],
        "deprecated": false,
        "summary": "Get permission scheme grants",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Permission schemes"
        ],
        "deprecated": false,
        "summary": "Create permission grant",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/permissionscheme/{schemeId}/permission/{permissionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Permission schemes"
        ],
        "deprecated": false,
        "summary": "Delete permission scheme grant",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Permission schemes"
        ],
        "deprecated": false,
        "summary": "Get permission scheme grant",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/priority": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue priorities"
        ],
        "deprecated": false,
        "summary": "Get priorities",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/priority/{id}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue priorities"
        ],
        "deprecated": false,
        "summary": "Get priority",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": true,
        "summary": "Get all projects",
        "x-atlassian-connect-scope": "READ",
        "x-changes": [
          {
            "announced": "2018-10-19T00:00:00.000Z",
            "details": "https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-removal-of-get-filters-and-get-all-projects/",
            "effective": "2019-04-19T00:00:00.000Z",
            "type": "removed"
          }
        ]
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": false,
        "summary": "Create project",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/project/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": false,
        "summary": "Get projects paginated",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/type": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project types"
        ],
        "deprecated": false,
        "summary": "Get all project types",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/type/accessible": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project types"
        ],
        "deprecated": false,
        "summary": "Get licensed project types",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/type/{projectTypeKey}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project types"
        ],
        "deprecated": false,
        "summary": "Get project type by key",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/type/{projectTypeKey}/accessible": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project types"
        ],
        "deprecated": false,
        "summary": "Get accessible project type by key",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectIdOrKey}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": false,
        "summary": "Delete project",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": false,
        "summary": "Get project",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": false,
        "summary": "Update project",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/project/{projectIdOrKey}/avatar": {
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project avatars"
        ],
        "deprecated": false,
        "summary": "Set project avatar",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/project/{projectIdOrKey}/avatar/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project avatars"
        ],
        "deprecated": false,
        "summary": "Delete project avatar",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/project/{projectIdOrKey}/avatar2": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project avatars"
        ],
        "deprecated": false,
        "summary": "Load project avatar",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/project/{projectIdOrKey}/avatars": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project avatars"
        ],
        "deprecated": false,
        "summary": "Get all project avatars",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectIdOrKey}/component": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project components"
        ],
        "deprecated": false,
        "summary": "Get project components paginated",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectIdOrKey}/components": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project components"
        ],
        "deprecated": false,
        "summary": "Get project components",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectIdOrKey}/delete": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": false,
        "summary": "Delete project asynchronously",
        "x-atlassian-connect-scope": "PROJECT_ADMIN",
        "x-experimental": true
      }
    },
    "/project/{projectIdOrKey}/properties": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project properties"
        ],
        "deprecated": false,
        "summary": "Get project property keys",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectIdOrKey}/properties/{propertyKey}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project properties"
        ],
        "deprecated": false,
        "summary": "Delete project property",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project properties"
        ],
        "deprecated": false,
        "summary": "Get project property",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project properties"
        ],
        "deprecated": false,
        "summary": "Set project property",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/project/{projectIdOrKey}/role": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project roles"
        ],
        "deprecated": false,
        "summary": "Get project roles for project",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectIdOrKey}/role/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project role actors"
        ],
        "deprecated": false,
        "summary": "Delete actors from project role",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project roles"
        ],
        "deprecated": false,
        "summary": "Get project role for project",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Project role actors"
        ],
        "deprecated": false,
        "summary": "Add actors to project role",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project role actors"
        ],
        "deprecated": false,
        "summary": "Set actors for project role",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/project/{projectIdOrKey}/roledetails": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project roles"
        ],
        "deprecated": false,
        "summary": "Get project role details",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectIdOrKey}/statuses": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": false,
        "summary": "Get all statuses for project",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectIdOrKey}/type/{newProjectTypeKey}": {
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": true,
        "summary": "Update project type",
        "x-atlassian-connect-scope": "PROJECT_ADMIN",
        "x-changes": [
          {
            "announced": "2019-06-03T00:00:00.000Z",
            "details": "https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-change-project-type-via-api//",
            "effective": "2019-12-03T00:00:00.000Z",
            "type": "removed"
          }
        ]
      }
    },
    "/project/{projectIdOrKey}/version": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": false,
        "summary": "Get project versions paginated",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectIdOrKey}/versions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": false,
        "summary": "Get project versions",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectId}/hierarchy": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": false,
        "summary": "Get project issue type hierarchy",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectKeyOrId}/issuesecuritylevelscheme": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Project permission schemes"
        ],
        "deprecated": false,
        "summary": "Get project issue security scheme",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectKeyOrId}/notificationscheme": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Projects"
        ],
        "deprecated": false,
        "summary": "Get project notification scheme",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/project/{projectKeyOrId}/permissionscheme": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Project permission schemes"
        ],
        "deprecated": false,
        "summary": "Get assigned permission scheme",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "tags": [
          "Project permission schemes"
        ],
        "deprecated": false,
        "summary": "Assign permission scheme",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/project/{projectKeyOrId}/securitylevel": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project permission schemes"
        ],
        "deprecated": false,
        "summary": "Get project issue security levels",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/projectCategory": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Project categories"
        ],
        "deprecated": false,
        "summary": "Get all project categories",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "tags": [
          "Project categories"
        ],
        "deprecated": false,
        "summary": "Create project category",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/projectCategory/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "tags": [
          "Project categories"
        ],
        "deprecated": false,
        "summary": "Delete project category",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Project categories"
        ],
        "deprecated": false,
        "summary": "Get project category by id",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "tags": [
          "Project categories"
        ],
        "deprecated": false,
        "summary": "Update project category",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/projectvalidate/key": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Project key and name validation"
        ],
        "deprecated": false,
        "summary": "Validate project key",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/projectvalidate/validProjectKey": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Project key and name validation"
        ],
        "deprecated": false,
        "summary": "Get valid project key",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/projectvalidate/validProjectName": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Project key and name validation"
        ],
        "deprecated": false,
        "summary": "Get valid project name",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/resolution": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue resolutions"
        ],
        "deprecated": false,
        "summary": "Get resolutions",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/resolution/{id}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue resolutions"
        ],
        "deprecated": false,
        "summary": "Get resolution",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/role": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Project roles"
        ],
        "deprecated": false,
        "summary": "Get all project roles",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "post": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Project roles"
        ],
        "deprecated": false,
        "summary": "Create project role",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/role/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Project roles"
        ],
        "deprecated": false,
        "summary": "Delete project role",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Project roles"
        ],
        "deprecated": false,
        "summary": "Get project role by ID",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "post": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Project roles"
        ],
        "deprecated": false,
        "summary": "Partial update project role",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "put": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Project roles"
        ],
        "deprecated": false,
        "summary": "Fully update project role",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/role/{id}/actors": {
      "delete": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Project role actors"
        ],
        "deprecated": false,
        "summary": "Delete default actors from project role",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Project role actors"
        ],
        "deprecated": false,
        "summary": "Get default actors for project role",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "post": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Project role actors"
        ],
        "deprecated": false,
        "summary": "Add default actors to project role",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/screens": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Get all screens",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/screens/addToDefault/{fieldId}": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Add field to default screen",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/screens/{screenId}/availableFields": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Get available screen fields",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/screens/{screenId}/tabs": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Get all screen tabs",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Create screen tab",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/screens/{screenId}/tabs/{tabId}": {
      "delete": {
        "security": [
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Delete screen tab",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Update screen tab",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/screens/{screenId}/tabs/{tabId}/fields": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Get all screen tab fields",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Add screen tab field",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/screens/{screenId}/tabs/{tabId}/fields/{id}": {
      "delete": {
        "security": [
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Remove screen tab field",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/screens/{screenId}/tabs/{tabId}/fields/{id}/move": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Move screen tab field",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/screens/{screenId}/tabs/{tabId}/move/{pos}": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Move screen tab",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/screenscheme": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Screens"
        ],
        "deprecated": false,
        "summary": "Get screen schemes",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue search"
        ],
        "deprecated": false,
        "summary": "Search for issues using JQL (GET)",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Issue search"
        ],
        "deprecated": false,
        "summary": "Search for issues using JQL (POST)",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/securitylevel/{id}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          },
          {}
        ],
        "tags": [
          "Issue security level"
        ],
        "deprecated": false,
        "summary": "Get issue security level",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/serverInfo": {
      "get": {
        "security": [
          {
            "OAuth2": []
          },
          {}
        ],
        "tags": [
          "Server info"
        ],
        "deprecated": false,
        "summary": "Get Jira instance info",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/settings/columns": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Issue navigator settings"
        ],
        "deprecated": false,
        "summary": "Get issue navigator default columns",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "put": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Issue navigator settings"
        ],
        "deprecated": false,
        "summary": "Set issue navigator default columns",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/status": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Workflow statuses"
        ],
        "deprecated": false,
        "summary": "Get all statuses",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/status/{idOrName}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Workflow statuses"
        ],
        "deprecated": false,
        "summary": "Get status",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/statuscategory": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Workflow status categories"
        ],
        "deprecated": false,
        "summary": "Get all status categories",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/statuscategory/{idOrKey}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Workflow status categories"
        ],
        "deprecated": false,
        "summary": "Get status category",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/task/{taskId}": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Tasks"
        ],
        "deprecated": false,
        "summary": "Get task",
        "x-atlassian-connect-scope": "NONE"
      }
    },
    "/task/{taskId}/cancel": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "Tasks"
        ],
        "deprecated": false,
        "summary": "Cancel task",
        "x-atlassian-connect-scope": "NONE",
        "x-experimental": true
      }
    },
    "/universal_avatar/type/{type}/owner/{entityId}": {
      "get": {
        "security": [
          {}
        ],
        "tags": [
          "Avatars"
        ],
        "deprecated": false,
        "summary": "Get avatars",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "post": {
        "security": [
          {}
        ],
        "tags": [
          "Avatars"
        ],
        "deprecated": false,
        "summary": "Load avatar",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/universal_avatar/type/{type}/owner/{owningObjectId}/avatar/{id}": {
      "delete": {
        "security": [
          {}
        ],
        "tags": [
          "Avatars"
        ],
        "deprecated": false,
        "summary": "Delete avatar",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/user": {
      "delete": {
        "security": [
          {}
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Delete user",
        "x-atlassian-connect-scope": "INACCESSIBLE",
        "x-experimental": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Get user",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {}
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Create user",
        "x-atlassian-connect-scope": "INACCESSIBLE",
        "x-experimental": true
      }
    },
    "/user/assignable/multiProjectSearch": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "User search"
        ],
        "deprecated": false,
        "summary": "Find users assignable to projects",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/user/assignable/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "User search"
        ],
        "deprecated": false,
        "summary": "Find users assignable to issues",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/user/bulk": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Bulk get users",
        "x-atlassian-connect-scope": "READ",
        "x-experimental": true
      }
    },
    "/user/bulk/migration": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Get account IDs for users",
        "x-atlassian-connect-scope": "READ",
        "x-experimental": true
      }
    },
    "/user/columns": {
      "delete": {
        "security": [
          {}
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Reset user default columns",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Get user default columns",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {}
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Set user default columns",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/user/email": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Get user email",
        "x-atlassian-connect-scope": "ACCESS_EMAIL_ADDRESSES",
        "x-experimental": true
      }
    },
    "/user/email/bulk": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Get user email bulk",
        "x-atlassian-connect-scope": "ACCESS_EMAIL_ADDRESSES",
        "x-experimental": true
      }
    },
    "/user/groups": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Get user groups",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/user/permission/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "User search"
        ],
        "deprecated": false,
        "summary": "Find users with permissions",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/user/picker": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "User search"
        ],
        "deprecated": false,
        "summary": "Find users for picker",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/user/properties": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "tags": [
          "User properties"
        ],
        "deprecated": false,
        "summary": "Get user property keys",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/user/properties/{propertyKey}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "User properties"
        ],
        "deprecated": false,
        "summary": "Delete user property",
        "x-atlassian-connect-scope": "DELETE"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "tags": [
          "User properties"
        ],
        "deprecated": false,
        "summary": "Get user property",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "tags": [
          "User properties"
        ],
        "deprecated": false,
        "summary": "Set user property",
        "x-atlassian-connect-scope": "WRITE"
      }
    },
    "/user/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "User search"
        ],
        "deprecated": false,
        "summary": "Find users",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/user/search/query": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "tags": [
          "User search"
        ],
        "deprecated": false,
        "summary": "Find users by query",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/user/search/query/key": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "tags": [
          "User search"
        ],
        "deprecated": false,
        "summary": "Find user keys by query",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/user/viewissue/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "User search"
        ],
        "deprecated": false,
        "summary": "Find users with browse permission",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/users": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Get all users default",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/users/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          },
          {}
        ],
        "tags": [
          "Users"
        ],
        "deprecated": false,
        "summary": "Get all users",
        "x-atlassian-connect-scope": "INACCESSIBLE"
      }
    },
    "/version": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": false,
        "summary": "Create version",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/version/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": true,
        "summary": "Delete version",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": false,
        "summary": "Get version",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": false,
        "summary": "Update version",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/version/{id}/mergeto/{moveIssuesTo}": {
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": false,
        "summary": "Merge versions",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/version/{id}/move": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": false,
        "summary": "Move version",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/version/{id}/relatedIssueCounts": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": false,
        "summary": "Get version's related issues count",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/version/{id}/removeAndSwap": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": false,
        "summary": "Delete and replace version",
        "x-atlassian-connect-scope": "PROJECT_ADMIN"
      }
    },
    "/version/{id}/unresolvedIssueCount": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          },
          {}
        ],
        "tags": [
          "Project versions"
        ],
        "deprecated": false,
        "summary": "Get version's unresolved issues count",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/webhook": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Webhooks"
        ],
        "deprecated": false,
        "summary": "Delete webhooks by ID",
        "x-atlassian-connect-scope": "READ"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Webhooks"
        ],
        "deprecated": false,
        "summary": "Get dynamic webhooks for app",
        "x-atlassian-connect-scope": "READ"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Webhooks"
        ],
        "deprecated": false,
        "summary": "Register dynamic webhooks",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/webhook/failed": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Webhooks"
        ],
        "deprecated": false,
        "summary": "Get failed webhooks",
        "x-atlassian-connect-scope": "READ",
        "x-experimental": true
      }
    },
    "/webhook/refresh": {
      "put": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Webhooks"
        ],
        "deprecated": false,
        "summary": "Extend webhook life",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/workflow": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflows"
        ],
        "deprecated": true,
        "summary": "Get all workflows",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflow/rule/config": {
      "get": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Workflow transition rules"
        ],
        "deprecated": false,
        "summary": "Get workflow transition rule configurations",
        "x-atlassian-connect-scope": "READ"
      },
      "put": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Workflow transition rules"
        ],
        "deprecated": false,
        "summary": "Update workflow transition rule configurations",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflow/search": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "tags": [
          "Workflows"
        ],
        "deprecated": false,
        "summary": "Get workflows paginated",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflow/transitions/{transitionId}/properties": {
      "delete": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Workflow transition properties"
        ],
        "deprecated": false,
        "summary": "Delete workflow transition property",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow transition properties"
        ],
        "deprecated": false,
        "summary": "Get workflow transition properties",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "post": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Workflow transition properties"
        ],
        "deprecated": false,
        "summary": "Create workflow transition property",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": []
          }
        ],
        "tags": [
          "Workflow transition properties"
        ],
        "deprecated": false,
        "summary": "Update workflow transition property",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Get all workflow schemes",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Create workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme/project": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme project associations"
        ],
        "deprecated": false,
        "summary": "Get workflow scheme project associations",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme/{id}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Delete workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Get workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Update workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme/{id}/createdraft": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Create draft workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme/{id}/default": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Delete default workflow",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Get default workflow",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Update default workflow",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme/{id}/draft": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Delete draft workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Get draft workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Update draft workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme/{id}/draft/default": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Delete draft default workflow",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Get draft default workflow",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Update draft default workflow",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme/{id}/draft/issuetype/{issueType}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Delete workflow for issue type in draft workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Get workflow for issue type in draft workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Set workflow for issue type in draft workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme/{id}/draft/workflow": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Delete issue types for workflow in draft workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Get issue types for workflows in draft workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow scheme drafts"
        ],
        "deprecated": false,
        "summary": "Set issue types for workflow in workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme/{id}/issuetype/{issueType}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Delete workflow for issue type in workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Get workflow for issue type in workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Set workflow for issue type in workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/workflowscheme/{id}/workflow": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Delete issue types for workflow in workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Get issue types for workflows in workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "tags": [
          "Workflow schemes"
        ],
        "deprecated": false,
        "summary": "Set issue types for workflow in workflow scheme",
        "x-atlassian-connect-scope": "ADMIN"
      }
    },
    "/worklog/deleted": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue worklogs"
        ],
        "deprecated": false,
        "summary": "Get IDs of deleted worklogs",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/worklog/list": {
      "post": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue worklogs"
        ],
        "deprecated": false,
        "summary": "Get worklogs",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/worklog/updated": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "tags": [
          "Issue worklogs"
        ],
        "deprecated": false,
        "summary": "Get IDs of updated worklogs",
        "x-atlassian-connect-scope": "READ"
      }
    },
    "/rest/atlassian-connect/1/addons/{addonKey}/properties": {
      "get": {
        "tags": [
          "App properties"
        ],
        "deprecated": false,
        "summary": "Get app properties",
        "x-atlassian-connect-scope": "NONE"
      }
    },
    "/rest/atlassian-connect/1/addons/{addonKey}/properties/{propertyKey}": {
      "delete": {
        "tags": [
          "App properties"
        ],
        "deprecated": false,
        "summary": "Delete app property",
        "x-atlassian-connect-scope": "NONE"
      },
      "get": {
        "tags": [
          "App properties"
        ],
        "deprecated": false,
        "summary": "Get app property",
        "x-atlassian-connect-scope": "NONE"
      },
      "put": {
        "tags": [
          "App properties"
        ],
        "deprecated": false,
        "summary": "Set app property",
        "x-atlassian-connect-scope": "NONE"
      }
    },
    "/rest/atlassian-connect/1/app/module/dynamic": {
      "delete": {
        "tags": [
          "Dynamic modules"
        ],
        "deprecated": false,
        "summary": "Remove modules",
        "x-atlassian-connect-scope": "NONE",
        "x-experimental": true
      },
      "get": {
        "tags": [
          "Dynamic modules"
        ],
        "deprecated": false,
        "summary": "Get modules",
        "x-atlassian-connect-scope": "NONE",
        "x-experimental": true
      },
      "post": {
        "tags": [
          "Dynamic modules"
        ],
        "deprecated": false,
        "summary": "Register modules",
        "x-atlassian-connect-scope": "NONE",
        "x-experimental": true
      }
    }
  },
  "tags": [
    {
      "description": "This resource represents application roles. Use it to get details of an application role or all application roles.",
      "name": "Application roles"
    },
    {
      "description": "This resource represents audits that record activities undertaken in Jira. Use it to get a list of audit records.",
      "name": "Audit records"
    },
    {
      "description": "This resource represents system and custom avatars. Use it to obtain the details of system or custom avatars as well as add and remove avatars from a project or issue type.",
      "name": "Avatars"
    },
    {
      "description": "This resource represents dashboards. Use it to obtain the details of dashboards as well as add and remove item properties from dashboards.",
      "name": "Dashboards"
    },
    {
      "description": "This resource represents [filters](https://confluence.atlassian.com/x/eQiiLQ). Use it to get, create, update, or delete filters. Also use it to configure the columns for a filter and set favorite filters.",
      "name": "Filters"
    },
    {
      "description": "This resource represents options for sharing [filters](#api-group-Filters). Use it to get share scopes as well as add and remove share scopes from filters.",
      "name": "Filter sharing"
    },
    {
      "description": "This resource represents a list of users and a list of groups. Use it to obtain the details to populate user and group picker suggestions list.",
      "name": "Group and user picker"
    },
    {
      "description": "This resource represents groups of users. Use it to get, create, find, and delete groups as well as add and remove users from groups.",
      "name": "Groups"
    },
    {
      "description": "This resource represents Jira issues. Use it to:\n\n *  create or edit issues, individually or in bulk.\n *  retrieve metadata about the options for creating or editing issues.\n *  delete an issue.\n *  assign a user to an issue.\n *  get issue changelogs.\n *  send notifications about an issue.\n *  get details of the transitions available for an issue.\n *  transition an issue.",
      "name": "Issues"
    },
    {
      "description": "This resource represents issue attachments and the attachment settings for Jira. Use it to get the metadata for an attachment, delete an attachment, and view the metadata for the contents of an attachment. Also, use it to get the attachment settings for Jira.",
      "name": "Issue attachments"
    },
    {
      "description": "This resource represents issue comments. Used it to:\n\n *  get, create, update, and delete a comment from an issue.\n *  get all comments from issue.\n *  get a list of comments by comment ID.",
      "name": "Issue comments"
    },
    {
      "description": "This resource represents [issue comment](#api-group-Issue-comments) properties, which provides for storing custom data against an issue comment. Use is to get, set, and delete issue comment properties as well as obtain the keys of all properties on a comment. Comment properties are a type of [entity property](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/).",
      "name": "Issue comment properties"
    },
    {
      "description": "This resource represents issue fields, both system and custom fields. Use it to get fields, field configurations, and create custom fields.",
      "name": "Issue fields"
    },
    {
      "description": "This resource represents issue field configurations. Use it to get, set, and delete field configurations and field configuration schemes.",
      "name": "Issue field configurations"
    },
    {
      "description": "This resource represents custom issue field select list options created in Jira or using the REST API. See [Issue custom field options (apps)](#api-group-Issue-custom-field-options--apps-) to manipulate custom issue field select list options created by a Connect app.\n\nA select list issue field is a type of [issue field](https://developer.atlassian.com/cloud/jira/platform/modules/issue-field/) that enables a user to select an option from a list. Use this resource to add an[...]",
      "name": "Issue custom field options"
    },
    {
      "description": "This resource represents custom issue field select list options created by a Connect app. See [Issue custom field options](#api-group-Issue-custom-field-options) to manipulate options created in Jira or using the REST API.\n\nA select list issue field is a type of [issue field](https://developer.atlassian.com/cloud/jira/platform/modules/issue-field/) that enables a user to select an option from a list. Use this resource to add, remove, and update the options of a select lis[...]",
      "name": "Issue custom field options (apps)"
    },
    {
      "description": "This resource represents links between issues. Use it to get, create, and delete links between issues.\n\nTo use this resource, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.",
      "name": "Issue links"
    },
    {
      "description": "This resource represents [issue link](#api-group-Issue-links) types. Use it to get, create, update, and delete link issue types as well as get lists of all link issue types.\n\nTo use this resource, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.",
      "name": "Issue link types"
    },
    {
      "description": "This resource represents issue navigator settings. Use it to get and set issue navigator default columns.",
      "name": "Issue navigator settings"
    },
    {
      "description": "This resource represents notification schemes, lists of events and the recipients who will receive notifications for those events. Use this resource to get details of a notification scheme and a list of notification schemes.",
      "name": "Issue notification schemes"
    },
    {
      "description": "This resource represents issue priorities. Use it to obtain a list of issue priorities and details for individual issue priorities.",
      "name": "Issue priorities"
    },
    {
      "description": "This resource represents [issue](#api-group-Issues) properties, which provides for storing custom data against an issue. Use it to get, set, and delete issue properties as well as obtain details of all properties on an issue. Operations to bulk update and delete issue properties are also provided. Issue properties are a type of [entity property](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/).",
      "name": "Issue properties"
    },
    {
      "description": "This resource represents remote issue links, a way of linking Jira to information in other systems. Use this resource to get, create, update, and delete remote issue links either by ID or global ID. The global ID provides a way of accessing remote issue links using information about the item's remote system host and remote system identifier.",
      "name": "Issue remote links"
    },
    {
      "description": "This resource represents issue resolution values. Use it to obtain a list of all issue resolution values and the details of individual resolution values.",
      "name": "Issue resolutions"
    },
    {
      "description": "This resource represents various ways to search for issues. Use it to search for issues with a JQL query and find issues to populate an issue picker.",
      "name": "Issue search"
    },
    {
      "description": "This resource represents issue security levels. Use it to obtain the details of any issue security level. For more information about issue security levels, see [Configuring issue-level security](https://confluence.atlassian.com/x/J4lKLg).",
      "name": "Issue security level"
    },
    {
      "description": "This resource represents issue security schemes. Use it to get an issue security scheme or list of issues security schemes.\n\nIssue security schemes control which users or groups of users can view an issue. When an issue security scheme is associated with a project, its security levels can be applied to issues in that project. Sub-tasks also inherit the security level of their parent issue.",
      "name": "Issue security schemes"
    },
    {
      "description": "This resource represents issues types. Use it to:\n\n *  get, create, update, and delete issue types.\n *  get all issue types for a user.\n *  get alternative issue types.\n *  set an avatar for an issue type.",
      "name": "Issue types"
    },
    {
      "description": "This resource represents issue type schemes. Use it to:\n\n *  get issue type schemes and a list of the projects that use them.\n *  associate issue type schemes with projects.",
      "name": "Issue type schemes"
    },
    {
      "description": "This resource represents issue type screen schemes. Use it to:\n\n *  get issue type screen schemes and a list of the projects that use them.\n *  associate issue type screen schemes with projects.",
      "name": "Issue type screen schemes"
    },
    {
      "description": "This resource represents [issue type](#api-group-Issue-types) properties, which provides for storing custom data against an issue type. Use it to get, create, and delete issue type properties as well as obtain the keys of all properties on a issues type. Issue type properties are a type of [entity property](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/).",
      "name": "Issue type properties"
    },
    {
      "description": "This resource represents votes cast by users on an issue. Use it to get details of votes on an issue as well as cast and withdrawal votes.",
      "name": "Issue votes"
    },
    {
      "description": "This resource represents users watching an issue. Use it to get details of users watching an issue as well as start and stop a user watching an issue.",
      "name": "Issue watchers"
    },
    {
      "description": "This resource represents issue worklogs. Use it to:\n\n *  get, create, update, and delete worklogs.\n *  obtain lists of updated or deleted worklogs.",
      "name": "Issue worklogs"
    },
    {
      "description": "This resource represents [issue worklog](#api-group-Issue-worklogs) properties, which provides for storing custom data against an issue worklog. Use it to get, create, and delete issue worklog properties as well as obtain the keys of all properties on a issue worklog. Issue worklog properties are a type of [entity property](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/).",
      "name": "Issue worklog properties"
    },
    {
      "description": "This resource is a collection of operations for [Jira expressions](https://developer.atlassian.com/cloud/jira/platform/jira-expressions/).",
      "name": "Jira expressions"
    },
    {
      "description": "This resource represents various settings in Jira. Use it to get and update Jira settings and properties.",
      "name": "Jira settings"
    },
    {
      "description": "This resource represents JQL search auto-complete details. Use it to obtain JQL search auto-complete data and suggestions for use in programmatic construction of queries or custom query builders. It also provides an operation to convert one or more JQL queries with user identifiers (username or user key) to equivalent JQL queries with account IDs.",
      "name": "JQL"
    },
    {
      "description": "This resource represents available labels. Use it to get available labels for the global label field.",
      "name": "Labels"
    },
    {
      "description": "This resource represents information about the current user, such as basic details, group membership, application roles, preferences, and locale. Use it to get, create, update, and delete (restore default) values of the user's preferences and locale.",
      "name": "Myself"
    },
    {
      "description": "This resource represents permissions. Use it to obtain details of all permissions and determine whether the user has certain permissions.",
      "name": "Permissions"
    },
    {
      "description": "This resource represents permission schemes. Use it to get, create, update, and delete permission schemes as well as get, create, update, and delete details of the permissions granted in those schemes.",
      "name": "Permission schemes"
    },
    {
      "description": "This resource represents projects. Use this resource to get, create, update, and delete projects. Also get statuses available to a project, a project's notification schemes, and update a project's type.",
      "name": "Projects"
    },
    {
      "description": "This resource represents avatars associated with a project. Use it to get, load, set, and remove project avatars.",
      "name": "Project avatars"
    },
    {
      "description": "This resource represents project categories. Use it to create, update, and delete project categories as well as obtain a list of all project categories and details of individual categories. For more information on managing project categories, see [Adding, assigning, and deleting project categories](https://confluence.atlassian.com/x/-A5WMg).",
      "name": "Project categories"
    },
    {
      "description": "This resource represents project components. Uses to get, create, update, and delete project components. Also get components for project and get a count of issues by component.",
      "name": "Project components"
    },
    {
      "description": "This resource provides validation for project keys and names.",
      "name": "Project key and name validation"
    },
    {
      "description": "This resource represents permission schemes for a project. Use this resource to:\n\n *  get details of a project's issue security levels available to the calling user.\n *  get the permission scheme associated with the project or assign different permission scheme to the project.\n *  get details of a project's issue security scheme.\n\nSee [Managing project permissions](https://confluence.atlassian.com/x/yodKLg) for more information about permission schemes.",
      "name": "Project permission schemes"
    },
    {
      "description": "This resource represents [project](#api-group-Projects) properties, which provides for storing custom data against a project. Use it to get, create, and delete project properties as well as get a list of property keys for a project. Project properties are a type of [entity property](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/).",
      "name": "Project properties"
    },
    {
      "description": "This resource represents the roles that users can play in projects. Use this resource to get, create, update, and delete project roles.",
      "name": "Project roles"
    },
    {
      "description": "This resource represents the users assigned to [project roles](#api-group-Issue-comments). Use this resource to get, add, and remove default users from project roles. Also use this resource to add and remove users from a project role associated with a project.",
      "name": "Project role actors"
    },
    {
      "description": "This resource represents project types. Use it to obtain a list of all project types, a list of project types accessible to the calling user, and details of a project type.",
      "name": "Project types"
    },
    {
      "description": "This resource represents project versions. Use it to get, get lists of, create, update, move, merge, and delete project versions. This resource also provides counts of issues by version.",
      "name": "Project versions"
    },
    {
      "description": "This resource represents the screens used to record issue details. Use this resource to:\n\n *  get details of all screens.\n *  get details of all the fields available for use on screens.\n *  add a field to the default screen.\n *  get, create, update, move, and delete screen tabs.\n *  get, add, move, and remove fields from screen tabs.",
      "name": "Screens"
    },
    {
      "description": "This resource provides information about the Jira instance.",
      "name": "Server info"
    },
    {
      "description": "This resource represents a [long-running asynchronous tasks](#async-operations). Use it to obtain details about the progress of a long-running task or cancel a long-running task.",
      "name": "Tasks"
    },
    {
      "description": "This resource represents time tracking and time tracking providers. Use it to get and set the time tracking provider, get and set the time tracking options, and disable time tracking.",
      "name": "Time tracking"
    },
    {
      "description": "This resource represent users. Use this resource to:\n\n *  get, get a list of, create, and delete users.\n *  get, set, and reset a user's default issue table columns.\n *  get a list of the groups the user belongs to.\n *  get a list of user account IDs for a list of usernames or user keys.",
      "name": "Users"
    },
    {
      "description": "This resource represents [user](#api-group-Users) properties and provides for storing custom data against a user. Use it to get, create, and delete user properties as well as get a list of property keys for a user. This resourse is designed for integrations and apps to store per-user data and settings. This enables data used to customized the user experience to be kept in the Jira Cloud instance's database. User properties are a type of [entity property](https://developer.a[...]",
      "name": "User properties"
    },
    {
      "description": "This resource represents various ways to search for and find users. Use it to obtain list of users including users assignable to projects and issues, users with permissions, user lists for pickup fields, and user lists generated using structured queries. Note that the operations in this resource only return users found within the first 1000 users.",
      "name": "User search"
    },
    {
      "description": "This resource represents webhooks. Webhooks are calls sent to a URL when an event occurs in Jira for issues specified by a JQL query. Only Connect apps can register webhooks. For more information, see [Webhooks](https://developer.atlassian.com/cloud/jira/platform/webhooks/#registering-a-webhook-via-the-jira-rest-api-for-connect-apps).",
      "name": "Webhooks"
    },
    {
      "description": "This resource represents workflows. Use it to get a list of workflows.",
      "name": "Workflows"
    },
    {
      "description": "This resource represents workflow transition rules. Workflow transition rules define a Connect app routine, such as a [workflow post functions](https://developer.atlassian.com/cloud/jira/platform/modules/workflow-post-function/) that is executed in association with the workflow. Use this resource to read and modify configuration of workflow transition rules.",
      "name": "Workflow transition rules"
    },
    {
      "description": "This resource represents workflow schemes. Use this resource to manage workflow schemes and the workflow scheme's workflows and issue types.\n\nA workflow scheme maps issue types to workflows. A workflow scheme can be associated with one or more projects, which enables the projects to use the workflow-issue type mappings.\n\nActive workflow schemes (workflow schemes that are used by projects) cannot be edited. When an active workflow scheme is edited, a draft copy of the sc[...]",
      "name": "Workflow schemes"
    },
    {
      "description": "This resource represents the associations between workflow schemes and projects.\n\nFor more information, see [Managing your workflows](https://confluence.atlassian.com/x/q4hKLg).",
      "name": "Workflow scheme project associations"
    },
    {
      "description": "This resource represents draft workflow schemes. Use this resource to manage drafts of workflow schemes.\n\nA workflow scheme maps issue types to workflows. A workflow scheme can be associated with one or more projects, which enables the projects to use the workflow-issue type mappings.\n\nActive workflow schemes (workflow schemes that are used by projects) cannot be edited. Edting an active workflow scheme creates a draft copy of the scheme. The draft workflow scheme can t[...]",
      "name": "Workflow scheme drafts"
    },
    {
      "description": "This resource represents issue workflow statuses. Use it to obtain a list of all statuses associated with workflows and the details of a status.",
      "name": "Workflow statuses"
    },
    {
      "description": "This resource represents status categories. Use it to obtain a list of all status categories and the details of a category. Status categories provided a mechanism for categorizing [statuses](#api-group-Workflow-statuses).",
      "name": "Workflow status categories"
    },
    {
      "description": "This resource represents workflow transition properties, which provides for storing custom data against a workflow transition. Use it to get, create, and delete workflow transition properties as well as get a list of property keys for a workflow transition. Workflow transition properties are a type of [entity property](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/).",
      "name": "Workflow transition properties"
    },
    {
      "description": "This resource represents app properties. Use it to store arbitrary data for your\n[Connect app](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect).",
      "name": "App properties"
    },
    {
      "description": "This resource represents [modules registered dynamically](https://developer.atlassian.com/cloud/jira/platform/dynamic-modules/)\nby [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect).",
      "name": "Dynamic modules"
    }
  ]
}
